services:
  - type: web
    name: latanime-bridge
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_KEY
        generateValue: true
      - key: PORT
        value: 3000
      - key: API_PASSWORD
        value: latanime
      - key: FORWARDED_ALLOW_IPS
        value: "*"
